language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - python3 pytchat_server.py -ip 127.0.0.1 -p 4444
  - python3 pytchat_client.py -ip 127.0.0.1 -p 4444
